table Data
	lineageTag: afaf1725-75a6-4ca6-b384-b8dca1e4e257

	column Conta
		dataType: int64
		formatString: 0
		lineageTag: 9d21cff1-4e2d-43b6-83e1-f60fb9f7d08b
		summarizeBy: none
		sourceColumn: Conta

		annotation SummarizationSetBy = Automatic

	column 'Descrição da conta'
		dataType: string
		lineageTag: 6f1044af-b6ab-436d-9baa-653dee2d6fa2
		summarizeBy: none
		sourceColumn: Descrição da conta

		annotation SummarizationSetBy = Automatic

	column 'Data lançamento'
		dataType: dateTime
		formatString: dd-mmm-yy
		lineageTag: 35447eb7-adf3-480f-a664-a4a946701f98
		summarizeBy: none
		sourceColumn: Data lançamento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Descrição
		dataType: string
		lineageTag: e322f909-4218-4fb4-a76b-32cc29a2d202
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	column Débito
		dataType: double
		lineageTag: a00410c6-a6bf-4a3f-bcee-4eda1c2b84df
		summarizeBy: sum
		sourceColumn: Débito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Crédito
		dataType: double
		lineageTag: 5084df35-3a56-41c5-94bd-ea6a9a023525
		summarizeBy: sum
		sourceColumn: Crédito

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Data do documento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0d8ad3d1-78c4-4f19-8f77-18371c2e008f
		summarizeBy: none
		sourceColumn: Data do documento

		variation Variation
			isDefault
			relationship: 500b79c7-3d5a-4abd-9811-4e70eaf59f77
			defaultHierarchy: LocalDateTable_a7ace612-ac71-4e8c-9b42-9ca5d8b962cd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nome do terceiro'
		dataType: string
		lineageTag: 4573d787-dc90-4f41-8097-d47d91894950
		summarizeBy: none
		sourceColumn: Nome do terceiro

		annotation SummarizationSetBy = Automatic

	partition Data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://elevateportugal-my.sharepoint.com/personal/zohaibhashmi_elevateaccounting_pt/Documents/Power%20BI/Client%2003/extratocontas_ADV_03_02_2025.xlsx"), null, true),
				    Dados_Sheet = Source{[Item="Dados",Kind="Sheet"]}[Data],
				    #"Removed Top Rows" = Table.Skip(Dados_Sheet,6),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Conta", "Data lançamento", "Débito", "Crédito", "Data do documento", "Nome do terceiro", "Descrição da conta", "Descrição"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([Data lançamento] <> null)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Data lançamento", type date}, {"Data do documento", type date}, {"Débito", type number}, {"Crédito", type number}, {"Nome do terceiro", type text}, {"Descrição da conta", type text}, {"Descrição", type text}, {"Conta", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

